# Generated by Django 2.2.1 on 2019-05-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('f_path', models.CharField(max_length=50)),
                ('f_create', models.CharField(max_length=25)),
                ('f_modify', models.CharField(max_length=25)),
                ('f_size', models.IntegerField()),
                ('f_archive', models.BooleanField(default=False)),
            ],
        ),
    ]
